### ISSUE TITLE
Квадратное уравнение

### ISSUE THREAD

**Issue by ankutalev** [Verkhozina/evverkhozina_19214#1]
1)Функция в своем названии должна отражать свое действие
2) Сигнатуру функции пока лучше не указывать - сейчас я не могу вызвать Вашу функцию с типом Int
3)Полностью игнорируется граничные случаи ввода, кроме отрицательного дискриминанта. Например 0 0 0, 0 1 0, 0 0 2

**Comment by Verkhozina** [comment]
Я постаралась исправить программу согласно вашим замечаниям. Проверьте, пожалуйста, файл "findroots.hs".

**Comment by ankutalev** [comment]
Случай 0 0 0 - особый, корней там бесконечное количество
В случае 0 b c  - можно посчитать корни линейного уравнения
Вот в случае 0 0 с уже ничего не посчитать.
Добавьте обработку этих случаев в Вашу программу. Совет - сразу используйте паттерн матчинг

например,

findroots 0 0 0 = error "Infinity"

Так гораздо проще, чем городить всякие сложные проверки

**Comment by ankutalev** [comment]
Напоминание про задачу

**Comment by Verkhozina** [comment]
Проверьте, пожалуйста, файл findroots2.hs

**Comment by ankutalev** [comment]
Почитайте в следующий раз про git. Он и нужен для того,чтобы не создавать файлы
findroots2.hs, findrootsFIXED.hs, findrootsFINALLYFIXED.hs и т.д.
Принято.
