### ISSUE TITLE
foldl /foldr map

### ISSUE THREAD

**Issue by ankutalev** [Verkhozina/evverkhozina_19214#2]
https://github.com/Verkhozina/evverkhozina_19214/blob/b48e3e95be6075946e3c7e0277479e96101e9829/homework%232.hs#L3

А без реверса сможете?

**Comment by Verkhozina** [comment]
Разве что через append:

 map_foldl f xs = foldl (\xs x -> append xs (f x)) [ ] xs

**Comment by ankutalev** [comment]
Сойдет
